name: 'example_checker'
description: 'Action to cross reference examples in source code, README.md and Cargo.toml to ensure they contain the same info.'
author: 'Andreas Weibye'
inputs:
  source:
    required: true
    description: 'path to source folder to be scanned, relative to the root of the repo'
    default: './examples/'
  targets:
    required: true
    description: 'Some description'
    default: '["./examples/README.md", "./Cargo.toml"]'
  file-types:
    required: false
    description: 'TODO'
    default: '[]'
  exclude-folders:
    required: false
    description: 'TODO'
    default: '[]'
  exclude-files:
    required: false
    description: 'TODO'
    default: '[]'
branding:
  icon: 'check-circle'
  color: 'orange'
runs:
  using: 'node12'
  main: 'dist/index.js'