name: 'example_checker'
description: 'Action to cross reference examples in source code, README.md and Cargo.toml to ensure they contain the same info.'
author: 'Andreas Weibye'
inputs:
  source_path:
    required: true
    description: 'path to source to be scanned'
    default: 'examples/'
  target_paths:
    required: true
    description: 
    default: '{["Cargo.toml", "examples/README.md"]}'
runs:
  using: 'node12'
  main: 'dist/index.js'