name: 'CI'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

jobs:
  build-and-test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
      - run: |
          npm run all
  run-action: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          source: './__tests__/validData/data/'
          file-types: '["test"]'
          exclude-folders: '["./__tests__/validData/data/ignorefolder"]'
          exclude-files: '["./__tests__/validData/data/should_be_ignored.test"]'
          targets: '[ { "Path": "./__tests__/validData/ValidToml.toml", "Style": 1 }, { "Path": "./__tests__/validData/ValidReadme.md", "Style": 0 }]'
          
